server:
  port: 8101
  servlet:
    context-path: /api
spring:
  application:
    name: onlinejudge-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinejudge
    username: root
    password: 123456789
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  secret: onlinejudge-jwt-secret-key-2026-256bits
  access-token-expire: 900
  refresh-token-expire: 604800
